---
abstract: kensiro-sinsu
author:
  - 'Tokuhiro Matsuno  C<< <tokuhirom __@__ gmail.com> >>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Kensiro
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Acme::Kensiro:
    file: lib/Acme/Kensiro.pm
    version: 0.14
requires:
  Exporter: 5.62
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Acme-Kensiro/issues
  homepage: https://github.com/tokuhirom/Acme-Kensiro
  repository: git://github.com/tokuhirom/Acme-Kensiro.git
version: 0.14
x_contributors:
  - 'otsune <otsune@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'tokuhirom <tokuhirom@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'tokuhirom <tokuhirom@gmail.com>'
