---
abstract: kensiro-sinsu
author:
  - 'Tokuhiro Matsuno  C<< <tokuhirom __@__ gmail.com> >>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  Module::Build: 0.4
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Kensiro
provides:
  Acme::Kensiro:
    file: lib/Acme/Kensiro.pm
    version: 0.11
requires:
  Exporter: 5.62
resources:
  bugtracker: https://github.com/tokuhirom/Acme-Kensiro/issues
  homepage: https://github.com/tokuhirom/Acme-Kensiro
  repository: git://github.com/tokuhirom/Acme-Kensiro.git
version: 0.11
