abstract: kensiro-sinsu
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Acme-Kensiro
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
version: 0.03
